import { CheckCircledIcon, ClockIcon, Cross2Icon, ExclamationTriangleIcon, FileTextIcon, ReloadIcon } from '@radix-ui/react-icons'
import { useEffect, useMemo, useState, useSyncExternalStore } from 'react'
import Markdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import type { CapabilityLanguage, CapabilityManifest, CapabilityModule, CapabilityPageProps } from '../../packages/capability-contract/src'
import manifestJson from './manifest.json'
import { dailyReviewJob, dailyReviewSnapshot, REVIEW_STORAGE_KEY, type PersistedDailyReview } from './review-store'
import './styles.css'

const manifest: CapabilityManifest = manifestJson

const messages = {
  zh: {
    eyebrow: '本地工作回顾',
    title: 'Codex 每日总结',
    subtitle: '从今天的会话里，还原真正推进过的工作。',
    run: '扫描并总结',
    refresh: '重新扫描并总结',
    publishing: '正在保存并发布总结…',
    cancelled: '任务已取消',
    interrupted: '上次执行已中断，可从检查点继续',
    cancel: '取消任务',
    retry: '从检查点重试',
    scanning: '正在扫描今天的 Codex sessions…',
    summarizing: '已提取任务，AI 正在生成总结…',
    ready: '今日总结已生成',
    empty: '今天还没有可总结的 Codex 会话。',
    error: '生成总结失败',
    retryHint: '请确认正在使用桌面版、能力权限和 AI Provider 均可用，然后重试。',
    sessions: '顶层会话',
    turns: '任务轮次',
    workspaces: '工作区',
    sourceTitle: '本次扫描',
    reviewTitle: '今日任务回顾',
    sourceHint: '已扫描全部当天文件；子 Agent 会话作为重复执行记录被排除。',
    archived: '已归档',
    active: '当前',
    generatedBy: '生成来源',
    waiting: '等待扫描结果',
  },
  en: {
    eyebrow: 'LOCAL WORK REVIEW',
    title: 'Codex Daily Review',
    subtitle: 'Reconstruct the work that actually moved forward in today’s sessions.',
    run: 'Scan and summarize',
    refresh: 'Scan and summarize again',
    publishing: 'Saving and publishing the review…',
    cancelled: 'Task cancelled',
    interrupted: 'Previous execution interrupted; resume from checkpoints',
    cancel: 'Cancel task',
    retry: 'Retry from checkpoints',
    scanning: 'Scanning today’s Codex sessions…',
    summarizing: 'Tasks extracted. AI is writing the review…',
    ready: 'Today’s review is ready',
    empty: 'There are no Codex sessions to summarize today.',
    error: 'Could not generate the review',
    retryHint: 'Confirm that the desktop app, Capability permissions, and AI Provider are available, then retry.',
    sessions: 'Root sessions',
    turns: 'Task turns',
    workspaces: 'Workspaces',
    sourceTitle: 'This scan',
    reviewTitle: 'Today’s task review',
    sourceHint: 'All files for today were scanned; child-agent sessions are excluded as duplicate execution records.',
    archived: 'Archived',
    active: 'Active',
    generatedBy: 'Generated by',
    waiting: 'Waiting for scan results',
  },
} satisfies Record<CapabilityLanguage, Record<string, string>>

function formatToday(date: string, locale: string) {
  return new Intl.DateTimeFormat(locale, { dateStyle: 'full' }).format(new Date(`${date}T12:00:00`))
}

function workspaceName(cwd: string) {
  const parts = cwd.split('/').filter(Boolean)
  return parts.at(-1) || cwd || '—'
}

function CodexDailyReviewPage({ host }: CapabilityPageProps) {
  const environment = useSyncExternalStore(host.environment.subscribe, host.environment.getSnapshot, host.environment.getSnapshot)
  const tasks = useSyncExternalStore(host.tasks.subscribe, host.tasks.getSnapshot, host.tasks.getSnapshot)
  const [legacy, setLegacy] = useState<PersistedDailyReview | null>(null)
  const [actionError, setActionError] = useState<string | null>(null)
  const date = new Date().toLocaleDateString('en-CA')
  const task = [...tasks].reverse().find((item) => item.job === 'daily-review' && (item.input as { date: string }).date === date)
  const copy = messages[environment.language]
  const { phase, source, summary, error } = dailyReviewSnapshot(task, legacy?.date === date ? legacy : null)
  const act = async (action: () => Promise<unknown>) => {
    setActionError(null)
    try { await action() } catch (reason) { setActionError(String(reason)) }
  }

  useEffect(() => {
    let current = true
    host.storage.get<PersistedDailyReview>(REVIEW_STORAGE_KEY).then((saved) => { if (current) setLegacy(saved) }).catch((reason) => { if (current) setActionError(String(reason)) })
    return () => { current = false }
  }, [host])

  const stats = useMemo(() => {
    const sessions = source?.sessions ?? []
    return {
      sessions: sessions.length,
      turns: sessions.reduce((total, session) => total + session.turns.length, 0),
      workspaces: new Set(sessions.map((session) => session.cwd).filter(Boolean)).size,
    }
  }, [source])

  const busy = task?.status === 'running'
  const statusText = phase === 'publishing' ? copy.publishing
    : phase === 'cancelled' ? copy.cancelled
    : phase === 'interrupted' ? copy.interrupted
    : phase === 'scanning' ? copy.scanning
    : phase === 'summarizing' ? copy.summarizing
      : phase === 'ready' ? copy.ready
        : phase === 'empty' ? copy.empty
          : phase === 'error' ? copy.error
            : copy.waiting

  return (
    <div className="codex-review-page" lang={environment.locale} data-theme={environment.theme}>
      <header className="codex-review-header">
        <div>
          <span className="codex-review-eyebrow">{copy.eyebrow}</span>
          <h1>{copy.title}</h1>
          <p>{copy.subtitle}</p>
        </div>
        <button className="codex-review-refresh" onClick={() => void act(() => host.tasks.start('daily-review', { date, language: environment.language }))} disabled={busy}>
          <ReloadIcon className={busy ? 'codex-review-spin' : ''} />
          {phase === 'idle' ? copy.run : copy.refresh}
        </button>
      </header>

      {actionError && <p role="alert">{actionError}</p>}
      <div className="codex-review-date"><ClockIcon />{formatToday(date, environment.locale)}</div>

      <section className={`codex-review-status codex-review-status-${phase}`} aria-live="polite">
        <span className="codex-review-status-icon">
          {phase === 'error' ? <ExclamationTriangleIcon /> : phase === 'ready' ? <CheckCircledIcon /> : <ReloadIcon className={busy ? 'codex-review-spin' : ''} />}
        </span>
        <div><strong>{statusText}</strong>{phase === 'error' && <small>{error}<br />{copy.retryHint}</small>}</div>
        {busy && <button className="codex-review-status-action" onClick={() => void act(() => host.tasks.cancel(task!.id))}><Cross2Icon aria-hidden="true" />{copy.cancel}</button>}
        {task && ['failed', 'interrupted', 'cancelled'].includes(task.status) && <button className="codex-review-status-action" onClick={() => void act(() => host.tasks.retry(task.id))}><ReloadIcon aria-hidden="true" />{copy.retry}</button>}
      </section>

      <div className="codex-review-stats">
        <div><span>{copy.sessions}</span><strong>{stats.sessions}</strong></div>
        <div><span>{copy.turns}</span><strong>{stats.turns}</strong></div>
        <div><span>{copy.workspaces}</span><strong>{stats.workspaces}</strong></div>
      </div>

      <div className="codex-review-layout">
        <section className="codex-review-summary">
          <div className="codex-review-section-heading">
            <div><span>DAILY REVIEW</span><h2>{copy.reviewTitle}</h2></div>
            {summary && <small>{copy.generatedBy} {summary.provider} · {summary.model}</small>}
          </div>
          {summary
            ? <div className="codex-review-output"><Markdown remarkPlugins={[remarkGfm]}>{summary.output}</Markdown></div>
            : <div className="codex-review-placeholder"><FileTextIcon /><span>{statusText}</span></div>}
        </section>

        <aside className="codex-review-sources">
          <div className="codex-review-section-heading"><div><span>SESSION SOURCES</span><h2>{copy.sourceTitle}</h2></div><small>{source?.scannedFileCount ?? 0}</small></div>
          <p>{copy.sourceHint}</p>
          <div className="codex-review-source-list">
            {source?.sessions.map((session) => <div className="codex-review-source" key={session.id}>
              <span><strong>{workspaceName(session.cwd)}</strong><small>{session.turns.length} {copy.turns}</small></span>
              <em>{session.archived ? copy.archived : copy.active}</em>
            </div>)}
          </div>
        </aside>
      </div>

    </div>
  )
}

const codexDailyReviewCapability: CapabilityModule = {
  manifest,
  jobs: { 'daily-review': dailyReviewJob },
  Page: (props: CapabilityPageProps) => <CodexDailyReviewPage {...props} />,
}

export default codexDailyReviewCapability

export { CodexDailyReviewPage, manifest }
